<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-6H0FSJA9" failures="1" tests="1" name="Test" time="7.219" errors="0" timestamp="2023-09-16T09:34:32 IST">
  <testcase classname="Testng.Saucedemo2" name="invalidcredinals" time="3.249">
    <failure type="java.lang.AssertionError" message="did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: did not expect [https://www.saucedemo.com/] but found [https://www.saucedemo.com/]
at Testng.Saucedemo2.invalidcredinals(Saucedemo2.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- invalidcredinals -->
</testsuite> <!-- Test -->
